# Generated by Django 4.1.2 on 2022-10-26 02:18

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to=category.models.categ_media),
        ),
    ]
